name: Build Documentation

on:
  repository_dispatch:
    types: [build-doc]
  workflow_dispatch:

jobs:
  buildDoc:
    runs-on: ubuntu-latest
    container:
      image: node:24-bookworm
    steps:
      - uses: actions/checkout@v5

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Build Documentation
        run: bash make.sh

      - name: Deploy Documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.documentation_token }}
          branch: gh-pages
          folder: mjml-doc
